#Goal - TO run End to End DevSecOps CI Pipeline for Devboard Application


name: DevSecOps CI Pipeline
on:
  push:
    branches: [main]


jobs:

  #code stage 
  code-quality:
    uses: ./.github/workflows/code-quality.yml

  #secret scanning 
  secret-scanning:
    uses: ./.github/workflows/secret-Scanning.yml