#Goal - To ensure no secrets are exposed in the codebase and to ensure that the secrets are not committed to the repository

name: Secret Scanning

on:
  workflow_call: # we can call this workflow before/after any other workflow

jobs:
  secret-scanning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0


      - name: GitLeaks Scan
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

